title: Commodity Product Markup Language (Test)
description: Version 6 Release 4.1 (v6.4.1)
#show_downloads: true
baseurl: "/CpML/"
siteurl: "https://knebelm.github.io/CpML/"
url: "https://knebelm.github.io/CpML/"

markdown: kramdown
theme: jekyll-theme-slate

exclude:
  - Gemfile
  - Gemfile.lock
