title: Commodity Product Markup Language (Test)
description: Version 6 Release 4.1 (v6.4.1)
show_downloads: true
markdown: kramdown
theme: jekyll-theme-slate
baseurl: "/CpML/"
siteurl: "https://knebelm.github.io/CpML/"